import * as THREE from 'three';
import { buildWeaponModel } from './src/weapons/models.js';
const g = buildWeaponModel('tec9', null, {viewmodel:false});
g.updateMatrixWorld(true);
const rows=[];
g.traverse(c=>{ if(!c.isMesh) return;
  const b=new THREE.Box3().setFromObject(c);
  rows.push([b.min.y.toFixed(3), b.max.y.toFixed(3), b.min.z.toFixed(3), b.max.z.toFixed(3), c.material===undefined?'':''].join(' '));
});
rows.sort((a,b)=>parseFloat(a)-parseFloat(b));
console.log('ymin ymax zmin zmax');
rows.slice(0,10).forEach(r=>console.log(r));
