export const COLORS = {
    TEAM_A: 0x0000ff,
    TEAM_B: 0xff0000,
    TEAM_A_LIGHT: '#8888ff',
    TEAM_B_LIGHT: '#ff8888',
    SKIN: 0xdbac82,
    CLOTH_DEFAULT: 0x556b2f,
    CLOTH_CT: 0x2f4f4f,
    CLOTH_T: 0x556b2f,
    VEST_COLOR: 0x1a1a1a,
    GUN_BODY: 0x222222,
    GUN_SLIDE: 0x333333,
    GUN_IRON: 0x111111,
    BLADE: 0xaaaaaa,
    HANDLE: 0x222222,
    NADE_BODY: 0x4b5320,
    CRATE: 0x8b4513,
    WALL_DEFAULT: 0xc2b280,
    SKY: 0xadd8e6,
    SAND: 0xedc9af
};

export const PHYSICS = {
    GRAVITY: 9.8 * 100.0,
    STANDING_HEIGHT: 18,
    CROUCHING_HEIGHT: 10,
    PLAYER_RADIUS: 4.0,
    MOVE_SPEED: 1000.0,
    CROUCH_SPEED: 500.0,
    JUMP_FORCE: 250.0
};

export const WEAPON_SETTINGS = {
    BLAST_RADIUS: 50
};

export const GRENADES_DATA = {
    'HE': {
        name: 'HE Grenade',
        fuse: 3000,
        damage: 100,
        radius: 60,
        color: '#4b5320',
        effect: 'explode'
    },
    'FLASH': {
        name: 'Flashbang',
        fuse: 2000,
        damage: 0,
        radius: 150,
        color: '#888888',
        effect: 'flash'
    },
    'SMOKE': {
        name: 'Smoke Grenade',
        fuse: 2500,
        damage: 0,
        radius: 80,
        color: '#222222',
        effect: 'smoke'
    },
    'MOLOTOV': {
        name: 'Molotov',
        fuse: 0, // Explodes on impact or short fuse
        damage: 15, // Damage per tick
        radius: 50,
        color: '#ffaa00',
        effect: 'fire'
    }
};

export const WEAPONS_DATA = {
    'GLOCK': {
        name: 'Glock-18',
        slot: 2,
        damage: 20,
        headshotMultiplier: 4,
        magSize: 20,
        reserveAmmo: 120,
        reloadTime: 2300,
        fireRate: 400, // RPM
        recoil: 0.05,
        spread: 0.02,
        isAutomatic: false,
        price: 200,
        type: 'pistol'
    },
    'USP': {
        name: 'USP-S',
        slot: 2,
        damage: 25,
        headshotMultiplier: 4,
        magSize: 12,
        reserveAmmo: 24,
        reloadTime: 2200,
        fireRate: 350,
        recoil: 0.04,
        spread: 0.01,
        isAutomatic: false,
        price: 200,
        type: 'pistol'
    },
    'DEAGLE': {
        name: 'Desert Eagle',
        slot: 2,
        damage: 60,
        headshotMultiplier: 4,
        magSize: 7,
        reserveAmmo: 35,
        reloadTime: 2500,
        fireRate: 260,
        recoil: 0.15,
        spread: 0.05,
        isAutomatic: false,
        price: 700,
        type: 'pistol'
    },
    'AK47': {
        name: 'AK-47',
        slot: 3,
        damage: 35,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 90,
        reloadTime: 2500,
        fireRate: 600,
        recoil: 0.1,
        spread: 0.03,
        isAutomatic: true,
        price: 2700,
        type: 'rifle'
    },
    'M4A4': {
        name: 'M4A4',
        slot: 3,
        damage: 30,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 90,
        reloadTime: 3100,
        fireRate: 666,
        recoil: 0.08,
        spread: 0.02,
        isAutomatic: true,
        price: 3100,
        type: 'rifle'
    },
    'AWP': {
        name: 'AWP',
        slot: 3,
        damage: 115,
        headshotMultiplier: 4,
        magSize: 5,
        reserveAmmo: 30,
        reloadTime: 3700,
        fireRate: 40,
        recoil: 0.5,
        spread: 0.001,
        isAutomatic: false,
        isBoltAction: true,
        price: 4750,
        type: 'sniper'
    },
    'P90': {
        name: 'P90',
        slot: 3,
        damage: 20,
        headshotMultiplier: 4,
        magSize: 50,
        reserveAmmo: 100,
        reloadTime: 3300,
        fireRate: 857,
        recoil: 0.04,
        spread: 0.04,
        isAutomatic: true,
        price: 2350,
        type: 'smg'
    },
    'XM1014': {
        name: 'XM1014',
        slot: 3,
        damage: 20,
        pellets: 6,
        headshotMultiplier: 2,
        magSize: 7,
        reserveAmmo: 32,
        reloadTime: 4000,
        fireRate: 171,
        recoil: 0.2,
        spread: 0.1,
        isAutomatic: true,
        price: 2000,
        type: 'shotgun'
    },
    'P250': {
        name: 'P250',
        slot: 2,
        damage: 38,
        headshotMultiplier: 4,
        magSize: 13,
        reserveAmmo: 26,
        reloadTime: 2200,
        fireRate: 400,
        recoil: 0.06,
        spread: 0.02,
        isAutomatic: false,
        price: 300,
        type: 'pistol'
    },
    'MAC10': {
        name: 'MAC-10',
        slot: 3,
        damage: 29,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 100,
        reloadTime: 2600,
        fireRate: 800,
        recoil: 0.05,
        spread: 0.05,
        isAutomatic: true,
        price: 1050,
        type: 'smg'
    },
    'MP9': {
        name: 'MP9',
        slot: 3,
        damage: 26,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 120,
        reloadTime: 2100,
        fireRate: 857,
        recoil: 0.04,
        spread: 0.04,
        isAutomatic: true,
        price: 1250,
        type: 'smg'
    },
    'GALIL': {
        name: 'Galil AR',
        slot: 3,
        damage: 30,
        headshotMultiplier: 4,
        magSize: 35,
        reserveAmmo: 90,
        reloadTime: 3000,
        fireRate: 666,
        recoil: 0.09,
        spread: 0.03,
        isAutomatic: true,
        price: 1800,
        type: 'rifle'
    },
    'FAMAS': {
        name: 'FAMAS',
        slot: 3,
        damage: 30,
        headshotMultiplier: 4,
        magSize: 25,
        reserveAmmo: 90,
        reloadTime: 3300,
        fireRate: 666,
        recoil: 0.07,
        spread: 0.02,
        isAutomatic: true,
        price: 2050,
        type: 'rifle'
    },
    'AUG': {
        name: 'AUG',
        slot: 3,
        damage: 28,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 90,
        reloadTime: 3800,
        fireRate: 600,
        recoil: 0.07,
        spread: 0.015,
        isAutomatic: true,
        price: 3300,
        type: 'rifle'
    },
    'SG553': {
        name: 'SG 553',
        slot: 3,
        damage: 30,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 90,
        reloadTime: 2800,
        fireRate: 545,
        recoil: 0.08,
        spread: 0.015,
        isAutomatic: true,
        price: 3000,
        type: 'rifle'
    },
    'SSG08': {
        name: 'SSG 08',
        slot: 3,
        damage: 88,
        headshotMultiplier: 4,
        magSize: 10,
        reserveAmmo: 90,
        reloadTime: 3700,
        fireRate: 48,
        recoil: 0.3,
        spread: 0.005,
        isAutomatic: false,
        isBoltAction: true,
        price: 1700,
        type: 'sniper'
    },
    'NEGEV': {
        name: 'Negev',
        slot: 3,
        damage: 35,
        headshotMultiplier: 4,
        magSize: 150,
        reserveAmmo: 200,
        reloadTime: 5700,
        fireRate: 800,
        recoil: 0.02,
        spread: 0.06,
        isAutomatic: true,
        price: 1700,
        type: 'heavy'
    },
    'MP7': {
        name: 'MP7',
        slot: 3,
        damage: 29,
        headshotMultiplier: 4,
        magSize: 30,
        reserveAmmo: 120,
        reloadTime: 3100,
        fireRate: 750,
        recoil: 0.05,
        spread: 0.03,
        isAutomatic: true,
        price: 1500,
        type: 'smg'
    },
    'M249': {
        name: 'M249',
        slot: 3,
        damage: 32,
        headshotMultiplier: 4,
        magSize: 100,
        reserveAmmo: 200,
        reloadTime: 5700,
        fireRate: 750,
        recoil: 0.08,
        spread: 0.05,
        isAutomatic: true,
        price: 5200,
        type: 'heavy'
    },
    'NOVA': {
        name: 'Nova',
        slot: 3,
        damage: 26,
        pellets: 8,
        headshotMultiplier: 2,
        magSize: 8,
        reserveAmmo: 32,
        reloadTime: 5000,
        fireRate: 68,
        recoil: 0.25,
        spread: 0.08,
        isAutomatic: false,
        price: 1050,
        type: 'shotgun'
    }
};



