export const GameState = {
    playerName: "Noob",
    playerKills: 0,
    networkScores: {},
    selectedMap: 'dust2',
    selectedMode: 'dm',
    teamsEnabled: false,
    playerTeam: 'A',
    teamScores: { A: 0, B: 0 },
    botsEnabled: true,
    isGameStarted: false,
    gameTimeLeft: 600,
    isPlayerDead: false,
    health: 100,
    cash: 800,
    ammoInClip: 20,
    ammoTotal: 120,
    isReloading: false,
    currentWeapon: 'gun',
    currentSlot: 2,
    isHost: false,
    lobbyCode: "",
    peer: null,
    connections: []
};
